# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0002_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='My slogan', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C5', 'Category 5'), ('C2', 'Category 2'), ('C3', 'Category 3'), ('C1', 'Category 1'), ('C4', 'Category 4')], max_length=2),
        ),
    ]
