# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-25 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyusaapp', '0007_auto_20171225_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C3', 'Category 3'), ('C5', 'Category 5'), ('C1', 'Category 1'), ('C4', 'Category 4'), ('C2', 'Category 2')], max_length=2),
        ),
        migrations.AddField(
            model_name='review',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyusaapp.Gig'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
