# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0009_auto_20171229_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C3', 'Category 3'), ('C5', 'Category 5'), ('C2', 'Category 2'), ('C4', 'Category 4'), ('C1', 'Category 1')], max_length=2),
        ),
    ]
