# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-31 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0014_auto_20171230_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C1', 'Category 1'), ('C5', 'Category 5'), ('C4', 'Category 4'), ('C2', 'Category 2'), ('C3', 'Category 3')], max_length=2),
        ),
    ]
