# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-21 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0019_auto_20180121_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C2', 'Category 2'), ('C1', 'Category 1'), ('C5', 'Category 5'), ('C4', 'Category 4'), ('C3', 'Category 3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('independent', 'Independent'), ('service', 'Service'), ('retail', 'Retail'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
