# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0021_auto_20180126_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('independent', 'Independent'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
