# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-26 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0025_auto_20180126_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C1', 'Category 1'), ('C3', 'Category 3'), ('C2', 'Category 2'), ('C5', 'Category 5'), ('C4', 'Category 4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('independent', 'Independent'), ('retail', 'Retail'), ('service', 'Service'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
