# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-26 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0026_auto_20180126_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C5', 'Category 5'), ('C2', 'Category 2'), ('C4', 'Category 4'), ('C1', 'Category 1'), ('C3', 'Category 3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2b', 'Business-to-Business'), ('b2c', 'Business-to-Consumer')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('retail', 'Retail'), ('manufacturer', 'Manufacturer'), ('service', 'Service'), ('independent', 'Independent'), ('wholesale', 'Wholesale')], default='manufacturer', max_length=12),
        ),
    ]
