# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0029_auto_20180126_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C2', 'Category 2'), ('C4', 'Category 4'), ('C1', 'Category 1'), ('C5', 'Category 5'), ('C3', 'Category 3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('service', 'Service'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer'), ('retail', 'Retail'), ('independent', 'Independent')], default='manufacturer', max_length=12),
        ),
    ]
