# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-28 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0032_auto_20180128_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C3', 'Category 3'), ('C5', 'Category 5'), ('C2', 'Category 2'), ('C1', 'Category 1'), ('C4', 'Category 4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2c', 'Business-to-Consumer'), ('b2b', 'Business-to-Business')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('retail', 'Retail'), ('service', 'Service'), ('independent', 'Independent'), ('wholesale', 'Wholesale')], default='manufacturer', max_length=12),
        ),
    ]
