# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0033_auto_20180128_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C5', 'Category 5'), ('C3', 'Category 3'), ('C4', 'Category 4'), ('C1', 'Category 1'), ('C2', 'Category 2')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.FileField(default='', upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('independent', 'Independent'), ('retail', 'Retail'), ('manufacturer', 'Manufacturer'), ('wholesale', 'Wholesale'), ('service', 'Service')], default='manufacturer', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='', max_length=500),
        ),
    ]
