# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0037_auto_20180128_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='photo',
            field=models.FileField(default='', upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('service', 'Service'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('independent', 'Independent')], default='manufacturer', max_length=12),
        ),
    ]
