# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0040_auto_20180128_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='photo',
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C2', 'Category 2'), ('C3', 'Category 3'), ('C4', 'Category 4'), ('C5', 'Category 5'), ('C1', 'Category 1')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2c', 'Business-to-Consumer'), ('b2b', 'Business-to-Business')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('service', 'Service'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer'), ('retail', 'Retail'), ('independent', 'Independent')], default='manufacturer', max_length=12),
        ),
    ]
