# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-29 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0042_auto_20180128_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C5', 'Category 5'), ('C3', 'Category 3'), ('C2', 'Category 2'), ('C1', 'Category 1'), ('C4', 'Category 4')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('service', 'Service'), ('independent', 'Independent'), ('manufacturer', 'Manufacturer'), ('retail', 'Retail')], default='manufacturer', max_length=12),
        ),
    ]
