# Generated by Django 2.0.2 on 2018-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0043_auto_20180129_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C1', 'Category 1'), ('C2', 'Category 2'), ('C4', 'Category 4'), ('C5', 'Category 5'), ('C3', 'Category 3')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('independent', 'Independent'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer'), ('service', 'Service')], default='manufacturer', max_length=12),
        ),
    ]
