# Generated by Django 2.0.2 on 2018-03-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0045_auto_20180322_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C4', 'Category 4'), ('C3', 'Category 3'), ('C5', 'Category 5'), ('C2', 'Category 2'), ('C1', 'Category 1')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('service', 'Service'), ('wholesale', 'Wholesale'), ('retail', 'Retail'), ('independent', 'Independent')], default='manufacturer', max_length=12),
        ),
    ]
