# Generated by Django 2.0.2 on 2018-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0046_auto_20180322_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='BrandPicture6',
            field=models.FileField(default='', upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C1', 'Category 1'), ('C3', 'Category 3'), ('C5', 'Category 5'), ('C2', 'Category 2'), ('C4', 'Category 4')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2b', 'Business-to-Business'), ('b2c', 'Business-to-Consumer')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('retail', 'Retail'), ('service', 'Service'), ('independent', 'Independent'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
