# Generated by Django 2.0.2 on 2018-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0048_auto_20180330_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='User name')),
                ('donatevalue', models.FloatField(verbose_name='Donate value')),
                ('cardtype', models.CharField(max_length=200, verbose_name='Card type')),
                ('cc_number', models.CharField(max_length=200, verbose_name='Card number')),
                ('cc_exp_date', models.CharField(max_length=200, verbose_name='Expire date')),
                ('cc_ccv', models.CharField(max_length=200, verbose_name='Card ccv')),
                ('holdername', models.CharField(max_length=200, verbose_name='Card holdername')),
            ],
        ),
        
    ]
