# Generated by Django 2.0.2 on 2018-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0049_auto_20180427_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('employees', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('psic', models.CharField(max_length=20)),
                ('brandnames', models.CharField(max_length=500)),
                ('salutation', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('suffix', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('titleext', models.CharField(max_length=500)),
                ('ImportSource', models.CharField(max_length=200)),
                ('ImportTimestamp', models.DateTimeField(auto_now_add=True)),
                ('ImportID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='BrandID',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='CompanyID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='CompanyID',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ImportedCompanyID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='LoginLink',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gig',
            name='BrandLogo',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='BrandPicture1',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='BrandPicture2',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='BrandPicture3',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='BrandPicture4',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='BrandPicture5',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='BrandPicture6',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C2', 'Category 2'), ('C4', 'Category 4'), ('C5', 'Category 5'), ('C1', 'Category 1'), ('C3', 'Category 3')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2b', 'Business-to-Business'), ('b2c', 'Business-to-Consumer')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyContactEmail',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('independent', 'Independent'), ('manufacturer', 'Manufacturer'), ('retail', 'Retail'), ('service', 'Service'), ('wholesale', 'Wholesale')], default='manufacturer', max_length=12),
        ),
    ]
