# Generated by Django 2.0.2 on 2018-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0050_auto_20180505_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='BrandID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C2', 'Category 2'), ('C5', 'Category 5'), ('C3', 'Category 3'), ('C4', 'Category 4'), ('C1', 'Category 1')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2c', 'Business-to-Consumer'), ('b2b', 'Business-to-Business')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('wholesale', 'Wholesale'), ('independent', 'Independent'), ('retail', 'Retail'), ('service', 'Service')], default='manufacturer', max_length=12),
        ),
    ]
