# Generated by Django 2.0.2 on 2018-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0053_auto_20180505_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C4', 'Category 4'), ('C3', 'Category 3'), ('C1', 'Category 1'), ('C5', 'Category 5'), ('C2', 'Category 2')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2b', 'Business-to-Business'), ('b2c', 'Business-to-Consumer')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('service', 'Service'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer'), ('retail', 'Retail'), ('independent', 'Independent')], default='manufacturer', max_length=12),
        ),
    ]
