# Generated by Django 2.0.2 on 2018-05-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0054_auto_20180508_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='Publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C4', 'Category 4'), ('C5', 'Category 5'), ('C3', 'Category 3'), ('C1', 'Category 1'), ('C2', 'Category 2')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('independent', 'Independent'), ('service', 'Service'), ('retail', 'Retail'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
